name: Deploy to Skynet

on:
  push:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - run: yarn
      - run: yarn build
        env:
          ALGOLIA_ADMIN_KEY: { { secrets.ALGOLIA_ADMIN_KEY } }
          DEFI_PULSE_API_KEY: { { secrets.DEFI_PULSE_API_KEY } }
          ETHERSCAN_API_KEY: { { secrets.ETHERSCAN_API_KEY } }
          GATSBY_ALGOLIA_APP_ID: { { secrets.GATSBY_ALGOLIA_APP_ID } }
          GATSBY_ALGOLIA_SEARCH_KEY: { { secrets.GATSBY_ALGOLIA_SEARCH_KEY } }
          GATSBY_GITHUB_TOKEN_READ_ONLY:
            { { secrets.GATSBY_GITHUB_TOKEN_READ_ONLY } }

      - name: "Deploy to Skynet"
        uses: SkynetLabs/deploy-to-skynet-action@v2
        with:
          upload-dir: public
          github-token: ${{ secrets.GITHUB_TOKEN }}
          registry-seed: ${{ secrets.SKYNET_REGISTRY_SEED || '' }}
          try-files: index.html /index.html
